server:
  port: 8082
spring:
  application:
    name: sample-web-api

  #国际化
  messages:
    basename: i18n/messages
  #模板
  thymeleaf:
    enabled: true #开启thymeleaf视图解析
    encoding: UTF-8 #编码
    prefix: classpath:/templates/  #前缀
    cache: false #是否使用缓存
    mode: HTML #严格的HTML语法模式
    suffix: .html #后缀名
    check-template: true