spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #ShardingSphere v5.2.1
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
    props:
      sql-show: true
    datasource:
      #数据库名称
      names: ds-0
      ds-0:
        jdbc-url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
    rules:
      sharding:
        # 绑定表规则列表
        binding-tables[0]: t_order
        tables:
          t_order:
            actual-data-nodes: ds-0.t_order_$->{2021..2022}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
            table-strategy:
              standard:
                sharding-column: create_time
                sharding-algorithm-name: t-order-interval
            #id生成策略
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        #默认分表策略（无）
        default-table-strategy:
          none:
        #分库策略
        default-database-strategy:
          standard:
            sharding-algorithm-name: database-inline
            sharding-column: user_id
        #分表算法
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds-$->{user_id % 1}
          t-order-interval:
            type: INTERVAL
            props:
              datetime-pattern: 'yyyy-MM-dd HH:mm:ss'
              datetime-lower: '2021-01-01 00:00:00'
              datetime-upper: '2022-12-31 23:59:59'
              sharding-suffix-pattern: yyyyMM
              datetime-interval-amount: 1
              datetime-interval-unit: MONTHS
        #雪花算法配置
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
              max-vibration-offset: 2048
