server:
  port: 8081
spring:
  application:
    name: sample-provider

  #ShardingSphere v5.0.0
  shardingsphere:
    props:
      sql-show: true
    datasource:
      #公共
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      #数据库名称
      names: ds0
      ds0:
        url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    rules:
      sharding:
        binding-tables: t_order
        tables:
          t_order:
            actual-data-nodes: ds0.t_order_$->{2021..2022}0$->{1..9},ds0.t_order_$->{2021..2022}$->{10..12}
            table-strategy:
              standard:
                sharding-column: create_time
                sharding-algorithm-name: t-order-interval
            #订单号生成策略
            key-generate-strategy:
              column: order_no
              key-generator-name: snowflake
        #分表算法
        sharding-algorithms:
          t-order-interval:
            type: INTERVAL
            props:
              datetime-pattern: yyyy-MM-dd HH:mm:ss
              datetime-lower: 2021-01-01 00:00:00
              datetime-upper: 2022-12-31 23:59:59
              sharding-suffix-pattern: yyyyMM
              datetime-interval-amount: 1
              datetime-interval-unit: MONTHS
        #雪花算法配置
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
              max-vibration-offset: 2048

#Quartz定时任务（配置独立的DataSource）
org:
  quartz:
    dataSource:
      driver: com.mysql.cj.jdbc.Driver
      URL: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      user: root
      password: root

#Mybatis-Plus
mybatis-plus:
  type-aliases-package: com.sample.lwj.entity
  mapper-locations: classpath*:/com/sample/lwj/mapper/*Mapper.xml
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
      id-type: auto


