server:
  port: 8081
spring:
  profiles:
    active: @environment@
  application:
    name: sample-provider
#Mybatis-Plus
mybatis-plus:
  type-aliases-package: com.sample.lwj.entity
  mapper-locations: classpath*:/com/sample/lwj/mapper/*Mapper.xml
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
      id-type: auto
  configuration:
    cache-enabled: true

